#!/bin/bash
git -C /usr/share/orchid/desktop/dwm/dwm-st-slstatus pull
git -C /usr/share/orchid/wallpapers pull
git -C /usr/share/orchid/orchid-bins pull && sudo cp /usr/share/orchid/orchid-bins/bins/* /usr/bin/
