#!/bin/bash
cd /etc
sudo rm -rf os-release && sudo rm -rf gentoo-release
sudo wget https://raw.githubusercontent.com/cAptive5976/orchid-reborn/main/testing/workaround/os-release &> /dev/null
sudo wget https://raw.githubusercontent.com/cAptive5976/orchid-reborn/main/testing/workaround/gentoo-release &> /dev/null
